## docker-compose version
version: '2'

services:
  nginx-ref:
    image: nginx-master
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8085:8085"
    networks:
      - some-network-ref
  hotel-service-ref:
    image: hotel-service
    ports:
      - "8081:80"
    networks:
      - some-network-ref


networks:
  some-network-ref:
    external:
      name: my-real-docker-network
